#version: '3.1'
networks:
  kosa_network:
    driver: bridge

services:
  was1:
    image: kimsuyoung/hello-web:latest
    networks:
      - kosa_network

  was2:
    image: kimsuyoung/hello-web:latest
    networks:
      - kosa_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - kosa_network
    depends_on:
      - was1
      - was2
