#version: '3.1'

	#사설망 network생성
network:
	kosa_network:
		driver: bridge
		
#서비스 선언
services:
	#was1 생성
	was1:
		image: kimsuyoung/hello-web:latest
		networks : 
			- kosa_network

						
	was2:
		image: kimsuyoung/hello-web:latest
		networks : 
			- kosa_network


	nginx:
		image: nginx:latest
		ports:
			- 80:80
		volumes:
			- ~/nginx/nginx.conf:/etc/nginx/nginx.conf
		networks:
			- kosa_network
		depends_on:
			- was1
			- wa2
			
#was2 생성
#nginx 생성