name: Our Workflow
on: 
  push:
    branches: [ main ]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: build gradlew
        run: ./gradlew bootJar

      - name: docker image run
        run: docekr build -t suyungking/hello-web:latest .

      - name: docker hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME  }}
          password: ${{ secrets.PASSWORD  }}
      
      - name: docker hub push
        run: docekr push suyungking/hello-web:latest
      
