name: Our Workflow
on: 
  push:
    branches: [ main ]
#환경설정변수
env:
  REPOSITORY_NAME: hello-web:latest

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: build gradlew
        run: ./gradlew bootJar

      - name: docker image run
        run: docker build -t ${{ secrets.USERNAME  }}/${{ env.REPOSITORY_NAME  }} .

      - name: docker hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME  }}
          password: ${{ secrets.PASSWORD  }}
      
      - name: docker hub push
        run: docker push ${{ secrets.USERNAME  }}/${{ env.REPOSITORY_NAME  }}
      
